const pet={
    nome: "Tony",
    nascimento: "18/02",
    raça: "Cachorro",
    especie: "Shitzu",
    dono: "Os Neves",
}

let lista={
    numero1: " Este é o numero 6",
    numero2: " Este é o numero 8",
    numero3: " Este é o numero 10",
    numero4: " Este é o numero 12",
    numero5: " Este é o numero 16",
}
console.log( lista.numero1)
console.log( lista.numero2)
console.log( lista.numero3)
console.log( lista.numero4)
console.log( lista.numero5)


alert( "nome: " + pet.nome + "\n" +
    "nascimento: " + pet.nascimento + "\n" +
    "raça: " + pet.raça + "\n" +
    "especie: " + pet.especie + "\n" +
    "dono: " + pet.dono + "\n"
 );

 